# Generated by Django 4.2.7 on 2025-09-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
