# Generated by Django 4.2.7 on 2025-09-28 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
